version: "3"

services:
    db:
        image: postgres
        restart: always
        shm_size: 128mb
        ports:
            - "5432:5432"
        environment:
            POSTGRES_DB: ${DATABASE_NAME}
            POSTGRES_USER: ${DATABASE_USERNAME}
            POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
        volumes:
            - pgdata:/var/lib/postgresql/data
        networks:
            - app-network

    rabbitmq:
        image: rabbitmq:3-management-alpine
        container_name: 'rabbitmq'
        ports:
            - "5672:5672"
            - "15672:15672"
        volumes:
            - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
            - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
        networks:
            - app-network

    nginx:
        image: nginx:latest
        ports:
            - "80:80"
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf:ro
        depends_on:
            - app
        networks:
            - app-network

    app:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8080:8080"
        environment:
            SPRING_PROFILES_ACTIVE: default
            DATABASE_URL: ${DATABASE_URL}
            DATABASE_USERNAME: ${DATABASE_USERNAME}
            DATABASE_PASSWORD: ${DATABASE_PASSWORD}
            MAIL_HOST: ${MAIL_HOST}
            MAIL_USERNAME: ${MAIL_USERNAME}
            MAIL_PASSWORD: ${MAIL_PASSWORD}
            MAIL_PROTOCOL: ${MAIL_PROTOCOL}
            MAIL_PORT: ${MAIL_PORT}
        depends_on:
            - db
            - rabbitmq
        networks:
            - app-network

volumes:
    pgdata:

networks:
    app-network:
        driver: bridge