version: "3"

services:
    db:
        image: postgres
        restart: always
        shm_size: 128mb
        container_name: 'postgresql'
        ports:
            - "5432:5432"
        environment:
            POSTGRES_DB: "pocketful"
            POSTGRES_USER: "postgres"
            POSTGRES_PASSWORD: "postgres"
        volumes:
            - pgdata:/var/lib/postgresql/data
        networks:
            - app-network

    rabbitmq:
        image: rabbitmq:3-management-alpine
        container_name: 'rabbitmq'
        ports:
            - "5672:5672"
            - "15672:15672"
        volumes:
            - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
            - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
        networks:
            - app-network

    app:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8080:8080"
        environment:
            SPRING_PROFILES_ACTIVE: "default"
            MAIL_HOST: "sandbox.smtp.mailtrap.io"
            MAIL_USERNAME: "04f7c522026d17"
            MAIL_PASSWORD: "63a2faa1e62b5cdo"
            MAIL_PROTOCOL: "smtp"
            MAIL_PORT: "25"
        depends_on:
            - db
        networks:
            - app-network

volumes:
    pgdata:

networks:
    app-network:
        driver: bridge