version: '3.8'

services:
    postgres:
        image: postgres:15
        restart: always
        shm_size: 128mb
        container_name: postgres_db
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: pocketful_dev
        ports:
            - "5432:5432"
        volumes:
            - pg_data:/var/lib/postgresql/data

    rabbitmq:
        image: rabbitmq:3-management
        container_name: rabbitmq_server
        restart: always
        ports:
            - "5672:5672"
            - "15672:15672"
        environment:
            RABBITMQ_DEFAULT_USER: ${RABBITMQ_USERNAME}
            RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
        volumes:
            - rabbitmq_data:/var/lib/rabbitmq

volumes:
    pg_data:
    rabbitmq_data:
