spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pocketful
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: false
        order_inserts: true
        order_updates: true
    show-sql: true

  flyway:
    baseline-on-migrate: true

  mail:
    host: sandbox.smtp.mailtrap.io
    username: 04f7c522026d17
    password: 63a2faa1e62b5c
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          port: 25
          auth: true
          starttls:
            enable: true
            required: true

  profiles:
    default: prod