spring:
  datasource:
    url: ${DATABASE_URL}
    hikari:
      maximum-pool-size: 10
      cache-prep-stmts: true
      prep-stmt-cache-size: 250
      prep-stmt-cache-sql-limit: 2048

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: false
        order_inserts: true
        order_updates: true
    show-sql: false

  flyway:
    baseline-on-migrate: true
    validateMigrationNaming: true
    out-of-order: false

  mail:
    host: ${MAIL_HOST}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        transport:
          protocol: ${MAIL_PROTOCOL}
        smtp:
          port: ${MAIL_PORT}
          auth: true
          starttls:
            enable: true
            required: true

  profiles:
    default: prod

security:
  token: ${JWT_SECRET}

rabbitmq:
  host: ${RABBITMQ_HOST}
  port: ${RABBITMQ_PORT}
  username: ${RABBITMQ_USERNAME}
  password: ${RABBITMQ_PASSWORD}

queue:
  payments_generation_queue: ${PAYMENTS_GENERATION_QUEUE}
  payments_edition_queue: ${PAYMENTS_EDITION_QUEUE}

scheduler:
  pending_payment_notification: ${PENDING_PAYMENT_NOTIFICATION_TIME}