spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: false
        order_inserts: true
        order_updates: true
    show-sql: true

  flyway:
    baseline-on-migrate: true

  mail:
    host: ${MAIL_HOST}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        transport:
          protocol: ${MAIL_PROTOCOL}
        smtp:
          port: ${MAIL_PORT}
          auth: true
          starttls:
            enable: true
            required: true

  profiles:
    default: prod